---
version: '3'

services:

  bulk-scan-orchestrator-service:
    build:
      context: ./
    links:
      - bulk-scan-orchestrator-db
    ports:
      - 8582:8582
    env_file:
      - .localenv

  bulk-scan-orchestrator-db:
    build:
      context: ./docker/database
    image: hmcts/dm-store-db:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5436:5432 # Different port to run more than one DB locally
