wiremock:
  url: &wiremock "http://localhost:${wiremock.port}"

core_case_data:
  api:
    url: *wiremock
document_management:
  url: *wiremock
  context-path: documents
idam:
  s2s-auth:
    url: *wiremock
  api:
    url: *wiremock
  users:
    bulkscan:
      username: bulkscanorchestrator+systemupdate@gmail.com
      password: Password12

scheduling:
  task:
    delete-envelopes-dlq-messages:
      enabled: false
    consume-envelopes-queue:
      enabled: false

azure:
  application-insights:
    instrumentation-key: integration-test
  servicebus:
    envelopes:
      max-delivery-count: 10

hystrix:
  command:
    default:
      execution.timeout.enabled: false
      fallback.enabled: true
      circuitBreaker.enabled: true
      metrics.rollingStats:
        timeInMilliseconds: 500
        numBuckets: 5
    check-jurisdiction-log-in:
      circuitBreaker:
        requestVolumeThreshold: 1
        sleepWindowInMilliseconds: 100000
        errorThresholdPercentage: 1

task:
  check-jurisdiction-log-in:
    check-validity-duration: PT0S

service-config:
  services:
    - service: bulkscan # service name corresponds to the name of the container in Blob Storage
      jurisdiction: BULKSCAN
      transformation-url: *wiremock
      case-type-ids:
        - Bulk_Scanned
